name: Identity Network - CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - "identity-network/**"
      - ".github/workflows/identity-network-ci.yaml"
  workflow_dispatch:
    inputs:
      terraform_cli_version:
        description: "Terraform CLI Version"
        required: true
        default: "latest"
        type: string

jobs:
  validate_and_plan:
    uses: Centrality-SG/cml-mgt-templates/.github/workflows/ci-template.yaml@main
    name: "CI"
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    with:
      root_module_folder_relative_path: "identity-network"
      terraform_cli_version: ${{ inputs.terraform_cli_version }}
